// This file is auto generated using the build project, do not edit this file directly.
// To regenerate it, run `dotnet run GenerateAwsAncestorTypes` in the root of the repository.
[<RequireQualifiedAccess>]
module AwsAncestorTypes

let ancestorsByType = Map.ofList [
    "aws:alb/listener:Listener", [
        "aws:lb/loadBalancer:LoadBalancer"
    ]
    "aws:alb/loadBalancer:LoadBalancer", [
        "aws:ec2/securityGroup:SecurityGroup"
        "aws:ec2/vpc:Vpc"
    ]
    "aws:alb/targetGroup:TargetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:apprunner/vpcConnector:VpcConnector", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:cloudhsmv2/cluster:Cluster", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:dax/subnetGroup:SubnetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:dms/replicationSubnetGroup:ReplicationSubnetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:docdb/clusterSnapshot:ClusterSnapshot", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/carrierGateway:CarrierGateway", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/defaultNetworkAcl:DefaultNetworkAcl", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/defaultRouteTable:DefaultRouteTable", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/defaultSecurityGroup:DefaultSecurityGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/defaultSubnet:DefaultSubnet", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/egressOnlyInternetGateway:EgressOnlyInternetGateway", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/flowLog:FlowLog", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/instance:Instance", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:ec2/internetGateway:InternetGateway", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/internetGatewayAttachment:InternetGatewayAttachment", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/launchConfiguration:LaunchConfiguration", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:ec2/localGatewayRouteTableVpcAssociation:LocalGatewayRouteTableVpcAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/mainRouteTableAssociation:MainRouteTableAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/networkAcl:NetworkAcl", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/networkInterface:NetworkInterface", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:ec2/routeTable:RouteTable", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/securityGroup:SecurityGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/spotInstanceRequest:SpotInstanceRequest", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:ec2/subnet:Subnet", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcDhcpOptionsAssociation:VpcDhcpOptionsAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcEndpoint:VpcEndpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcIpv4CidrBlockAssociation:VpcIpv4CidrBlockAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcIpv6CidrBlockAssociation:VpcIpv6CidrBlockAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcPeeringConnection:VpcPeeringConnection", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpcPeeringConnectionAccepter:VpcPeeringConnectionAccepter", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpnGateway:VpnGateway", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2/vpnGatewayAttachment:VpnGatewayAttachment", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2clientvpn/endpoint:Endpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2clientvpn/networkAssociation:NetworkAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2transitgateway/instanceConnectEndpoint:InstanceConnectEndpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2transitgateway/vpcAttachment:VpcAttachment", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:ec2transitgateway/vpcAttachmentAccepter:VpcAttachmentAccepter", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:efs/mountTarget:MountTarget", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:elasticache/subnetGroup:SubnetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:elb/loadBalancer:LoadBalancer", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:emr/studio:Studio", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:fsx/fileCache:FileCache", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:fsx/lustreFileSystem:LustreFileSystem", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:fsx/ontapFileSystem:OntapFileSystem", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:fsx/openZfsFileSystem:OpenZfsFileSystem", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:fsx/windowsFileSystem:WindowsFileSystem", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:glue/devEndpoint:DevEndpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:lb/listener:Listener", [
        "aws:lb/targetGroup:TargetGroup"
        "aws:lb/loadBalancer:LoadBalancer"
    ]
    "aws:lb/loadBalancer:LoadBalancer", [
        "aws:ec2/vpc:Vpc"
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:lb/targetGroup:TargetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:m2/environment:Environment", [
        "aws:lb/loadBalancer:LoadBalancer"
    ]
    "aws:memorydb/subnetGroup:SubnetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:mq/broker:Broker", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:msk/vpcConnection:VpcConnection", [
        "aws:ec2/securityGroup:SecurityGroup"
        "aws:ec2/vpc:Vpc"
    ]
    "aws:neptune/clusterSnapshot:ClusterSnapshot", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:networkfirewall/firewall:Firewall", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:opensearch/serverlessVpcEndpoint:ServerlessVpcEndpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:opsworks/stack:Stack", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:rds/clusterSnapshot:ClusterSnapshot", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:rds/proxyEndpoint:ProxyEndpoint", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:rds/snapshot:Snapshot", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:rds/snapshotCopy:SnapshotCopy", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:rds/subnetGroup:SubnetGroup", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:route53/resolverFirewallRuleGroupAssociation:ResolverFirewallRuleGroupAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:route53/resolverRuleAssociation:ResolverRuleAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:route53/vpcAssociationAuthorization:VpcAssociationAuthorization", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:route53/zoneAssociation:ZoneAssociation", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:sagemaker/domain:Domain", [
        "aws:ec2/vpc:Vpc"
    ]
    "aws:sagemaker/notebookInstance:NotebookInstance", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:vpc/securityGroupEgressRule:SecurityGroupEgressRule", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
    "aws:vpc/securityGroupIngressRule:SecurityGroupIngressRule", [
        "aws:ec2/securityGroup:SecurityGroup"
    ]
]
